import Head from "next/head";
import Image from "next/image";
import { Header, HomeContent, HomeFooter, Footer } from "../components";
import { Grid, Box } from "@mui/material";
import {
  FaFacebookF,
  FaTwitter,
  FaYoutube,
  FaLinkedin,
  FaInstagram,
} from "react-icons/fa";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Vocally</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{ flexGrow: 1 }}>
        <Grid
          container
          style={{ flexGrow: 1 }}
          xs
          md={12}
          sm={12}
          width="90%"
          margin="0 auto"
        >
          <Header />

          {/* Main Content */}
          <Grid container pt="4em">
            <Grid item xs={12} sm={12} md={12} lg={6} xl={6} pb="2em">
              <HomeContent />
            </Grid>
            <Grid item xs={12} sm={12} md={12} lg={6} xl={6}>
              <div className="image-container">
                <Image fill src="/image_1.png" alt="hero" className="image" />
              </div>
            </Grid>
          </Grid>

          <Grid width="100%" display="flex" justifyContent="flex-end">
            <Grid padding="0px 10px">
              <FaFacebookF />
            </Grid>
            <Grid padding="0px 10px">
              <FaTwitter />
            </Grid>
            <Grid padding="0px 10px">
              <FaYoutube />
            </Grid>
            <Grid padding="0px 10px">
              <FaLinkedin />
            </Grid>
            <Grid padding="0px 10px">
              <FaInstagram />
            </Grid>
          </Grid>
        </Grid>

        <Grid pt="5em">
          <hr />
        </Grid>

        <Grid width="80%" container margin="0 auto" pt="4em">
          <Grid item xs sm md={12} lg={6} xl={6}>
            <div className="image-container-2">
              <Image fill src="/image_2.png" alt="hero" className="image" />
            </div>
          </Grid>
          <Grid item xs sm md={12} lg={6} xl={6}>
            <HomeFooter />
          </Grid>
        </Grid>

        <Grid pt="4em">
          <hr />
        </Grid>

        <Footer />
      </Box>
    </div>
  );
}
